#spring.application.name=univ-board
#application port -> 8080(default)
server:
  port: 8082

#database setting
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/madangdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: madang
    password: madang

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    url: ${KAKAO_REDIRECT_URL}